In [18]:
import pytse_client as tse 
import numpy as np 
from technical_analysis import * 
from ticker_statistics import *

In [19]:
%reload_ext autoreload
%autoreload 2

In [20]:
symbol = "شستا"
data = pd.read_csv("tickers_data/" + symbol + ".csv", 
                   parse_dates=True, 
                   index_col="date")
data

,open,high,low,adjClose,value,volume,count,yesterday,close
date,,,,,,,,,
2020-04-15,8600.0,8600.0,8600.0,8600.0,57619891863600,6699987426,2061657,1000.0,8600.0
2020-04-18,9030.0,9030.0,9030.0,8889.0,84687412530,9378451,2122,8600.0,9030.0
2020-04-19,9333.0,9333.0,9333.0,9027.0,40548235797,4344609,2796,8889.0,9333.0
2020-04-20,9478.0,9478.0,9478.0,9269.0,71072242612,7498654,3759,9027.0,9478.0
2020-04-21,9732.0,9732.0,9732.0,9483.0,62696434404,6442297,3290,9269.0,9732.0
...,...,...,...,...,...,...,...,...,...
2023-10-07,1310.0,1310.0,1282.0,1288.0,406492878575,315529322,4852,1297.0,1283.0
2023-10-08,1270.0,1270.0,1243.0,1251.0,822595420594,657461430,9159,1288.0,1249.0
2023-10-09,0.0,1285.0,1244.0,1267.0,457514177348,361020673,5605,1251.0,1273.0
2023-10-10,1282.0,1310.0,1260.0,1291.0,353154149571,273594764,4313,1267.0,1304.0
2023-10-11,1301.0,1309.0,1283.0,1291.0,377204202973,292070187,4839,1291.0,1289.0

In [21]:
ta = TechnicalAnalysis(data)
ta.macd_simple()

-1

In [22]:
stats = ReturnStatistic(data)
stats.compute_returns_stats()

                       portfolio_stats
statistics
Cumulative Return            -0.850116
Annualized Return            -0.491109
Maximum Drawdown              0.987809
Annualized Volatility         0.747848
Sharpe Ratio                 -0.656696
Sortino Ratio                -0.555302
Kurtosis                    206.617634
Skewness                    -11.277706
VaR Historical                0.042430
CVaR Historical               0.005874
VaR Gaussian                  0.077359
CVaR Gaussian                 0.000183
VaR Nongaussian              -0.080482
CVaR Nongaussian              0.357721

In [23]:
fund = FundamentalData(symbol)
fund.symbol_information()
fund.fundamental_data()
fund.fundamental_table()

{'symbol': 'سرمایه گذاری تامین اجتماعی',
 'group': 'شركتهاي چند رشته اي صنعتي',
 'financial_year': '03/31',
 'eps': 180.0,
 'p_e': 7.1722222222222225,
 'group p_e': 6.78,
 'market cap': 2112093371696000.0}